name: Claude Code
on:
  issue_comment: # Issue（課題や質問）にコメントがあったとき
    types: [created]
  pull_request_review_comment: # Pull Request（変更提案）のレビューコメントがあったとき
    types: [created]
  issues: # Issueが作られたり、担当者が割り当てられたとき
    types: [opened, assigned]
  pull_request_review: # Pull Requestのレビューが提出されたとき
    types: [submitted]

jobs:
  claude:
    if: | # 以下のようなコメントやタイトルに「@claude」が含まれていたら動く
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))

    runs-on: ubuntu-latest # 実行する環境

    permissions: # Claudeが作業するために必要な権限
      contents: write
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Checkout repository # まずリポジトリの情報を読み込む
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # 最新の情報だけ取得

      - name: Run Claude Code # Claudeを実行する
        id: claude
        uses: tekitoo7777/claude-code-action@main # Step 0でコピーした設計図を指定
        with:
          use_oauth: 'true' # 「通行証」を使う設定
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }} # Step 4で設定したシークレット
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }} # Step 4で設定したシークレット
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }} # Step 4で設定したシークレット
